# Configuração da URL de conexão (salva os dados em memória durante a execução)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o Console do H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate / JPA
# update: Cria as tabelas automaticamente com base nas suas classes @Entity e atualiza se necessário
spring.jpa.hibernate.ddl-auto=update

# Mostra os comandos SQL gerados pelo Spring no console/terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true